config/routes.rb
WildDustPayroll::Application.routes.draw do

  devise_for :users
  root "employees#index"
  get "/about" => "about#index"

  resources :clothing_types
  resources :employees do
  	resources :sewed_clothings
  end
end

app/models/clothing_type.rb
class ClothingType < ActiveRecord::Base
  validates_presence_of :name,
                        :unit_price
  has_many :sewed_clothings
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :sewed_clothings, dependent: :destroy
  validates_presence_of :first_name,
                        :last_name

	def full_name
		"#{first_name} #{last_name}"
	end
end

app/models/sewed_clothing.rb
class SewedClothing < ActiveRecord::Base
  validates_presence_of :owner_name, :quantity, :clothing_type_id
  validates :quantity, numericality: true
  belongs_to :employee
  belongs_to :clothing_type
  scope      :current_sewed, -> { where("created_at BETWEEN '#{DateTime.now.midnight.to_s(:db)}' AND '#{((DateTime.now.midnight)+1).to_s(:db)}'") }

  def total
    clothing_type.unit_price * quantity
  end

  def self.sewed_on_date(date)
    where("DATE(created_at) = ?", date)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :trackable,
         :validatable,
         :authentication_keys => [:login]

  validates :username,
            :uniqueness => {
              :case_sensitive => false
            }

  attr_accessor :login

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end


  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/clothing_types_controller.rb
class ClothingTypesController < ApplicationController
  before_action :authenticate_user!,
                :set_clothing_type, only:[:edit, :update]  
	def index
    @clothing_types = ClothingType.all
  end

  def new
    @clothing_type = ClothingType.new
  end

  def create
    @clothing_type = ClothingType.new(clothing_type_params)
    @clothing_type.save
    redirect_to clothing_types_path
  end

  def edit    
  end

  def update
    @clothing_type.update(clothing_type_params)
    redirect_to clothing_types_path
  end

  private
  def clothing_type_params
    params.require(:clothing_type).permit(:name, :description, :unit_price)
  end

  def set_clothing_type
    @clothing_type = ClothingType.find(params[:id])
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!

  def index
    @employees = Employee.all
  end

  def show
    @employee = Employee.find(params[:id])
    @sewed_date = params[:sew_date].blank? ? Time.now : params[:sew_date].to_date
    @sewed_clothings_on_date = @employee.sewed_clothings.sewed_on_date(@sewed_date.strftime("%Y-%m-%d"))
    @sewed_clothing = @employee.sewed_clothings.new
    @sewed_clothing_dates = sewed_clothing_dates(@employee).uniq
  end

  def sewed_clothing_dates(employee)
    employee.sewed_clothings.pluck(:created_at).map do |date|
      date.to_date
    end    
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    @employee.save
    redirect_to @employee
  end

  def edit
    @employee =  Employee.find(params[:id])
  end

  def destroy
    Employee.find(params[:id]).destroy
    redirect_to employees_url
  end

  def update
    @employee = Employee.find(params[:id])
    @employee.update(employee_params)
    redirect_to employee_url @employee
  end

  private
  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :address, :contact_details, :birthday)
  end
end

app/controllers/sewed_clothings_controller.rb
class SewedClothingsController < ApplicationController
  def create
    @clothing_type = ClothingType.find(sewed_clothing_params[:clothing_type_id])
    @employee = Employee.find(params[:employee_id])
    @sewed_date = params[:sew_date].blank? ? Time.now : params[:sew_date].to_date
    @sewed_clothings_on_date = @employee.sewed_clothings.sewed_on_date(@sewed_date.strftime("%Y-%m-%d"))
    @sewed_clothing = @employee.sewed_clothings.create(sewed_clothing_params)
    # render :template => "employees/show"
    redirect_to @employee
  end

  def edit
    common_variables
    render :template => "employees/show"
  end

  def update
    common_variables
    @sewed_clothing.update(sewed_clothing_params)
    redirect_to @employee
  end

  def destroy
    common_variables
    @sewed_clothing.destroy
    redirect_to @employee
  end

  private
    def common_variables
      @employee = Employee.find(params[:employee_id])
      @sewed_clothing = @employee.sewed_clothings.find(params[:id])
      @sewed_date = params[:sew_date].blank? ? Time.now : params[:sew_date].to_date
      @sewed_clothings_on_date = @employee.sewed_clothings.sewed_on_date(@sewed_date.strftime("%Y-%m-%d"))
    end

    def sewed_clothing_params
      params.require(:sewed_clothing).permit(:owner_name, :clothing_type_id, :quantity)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_link(path)
    "active" if current_page?(path)
  end

  def prompts(notice, alert)
    content_tag(:div, content_tag(:p, notice), class: "alert alert-info") unless notice.blank?
    content_tag(:div, content_tag(:p, alert), class: "alert alert-danger") unless alert.blank?
  end
end

app/helpers/clothing_types_helper.rb
module ClothingTypesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
  def sewed_clothing_total(sewed_clothing)
    total = 0.0
    sewed_clothing.each do |sc|
      total += sc.total
    end
    total
  end

  def format_address
    check_and_display @employee.address      
  end

  def format_age
    age = check_and_display(@employee.birthday)
    unless  age == 'N/A'
      distance_of_time_in_words(Date.current, @employee.birthday) + " old"
    else
      age
    end
  end

  def format_birthday
    check_and_display @employee.birthday
  end

  def format_contact_details
    check_and_display @employee.contact_details
  end

  def check_and_display(detail)
    if detail.nil? || detail.blank?
      'N/A'
    else     
      detail
    end
  end
end

app/helpers/sewed_clothings_helper.rb
module SewedClothingsHelper
end

app/views/about/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h2>About the Software</h2></div>
    <div class="panel-body">

      <div class="panel panel-default">
        <div class="panel-heading"><h2>Purpose</h2></div>
        <div class="panel-body">
          <p>The purpose of this software is to provide a payroll system for Wild Dust Tailoring. The software is customized to fit the current payroll flow of the business. The system can record and compute employees' sewed clothings for a particular pay day and also the employer can review the transaction history.</p>
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading"><h2>Written by</h2></div>
        <div class="panel-body">
          <p><strong>Jay Paul Aying</strong>, Ruby on Rails programmer <br/>
          Linked: <strong>ph.linkedin.com/pub/jay-paul-aying</strong><br/>
          g+: <strong>+jaypaulaying</strong><br/>
          fb: <strong>fb.com/jiefool</strong><br/>
          twitter: <strong>@jaypaulaying</strong><br/>
          email: <strong>jaypaulaying5@gmail.com</strong><br/></p>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/clothing_types/_clothing_type.html.erb
<%= content_tag_for(:tr, clothing_type, index) %>
  <div class="col-md-1"><%= index + 1 %></div>
  <div class="col-md-3"><%= clothing_type.name %></div>
  <div class="col-md-2"><%= number_to_currency(clothing_type.unit_price, unit: "₱ ") %></div>
  <div class="col-md-3"><%= clothing_type.description %></div>
  <div class="col-md-3">    
      <%= link_to 'Edit', edit_clothing_type_path(clothing_type), class: "btn btn-warning btn-block" %>
  </div>

app/views/clothing_types/_form.html.erb
<%= form_for(@clothing_type) do |f| %>
  <% if @clothing_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clothing_type.errors.count, 'error') %> <%= 'prohibited this Clothing type from being saved' %>:</h2>
      <ul>
      <% @clothing_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name, class: "form-control", require: true, placeholder: "e.g. \"Polo, Sando\"" %>
  </p>
  <p>
    <%= f.label :unit_price %><br/>
    <%= f.text_field :unit_price, class: "form-control", require: true, placeholder: "e.g. \"25, 35\"" %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_field :description, class: "form-control",  placeholder: "e.g. \"Basketball uniform down\""%>
  </p>
  <hr />
  <p>
    <%= f.submit class: "btn btn-lg btn-success btn-block cancel-button" %>
  </p>
<% end %>

app/views/clothing_types/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <div class="panel panel-default clothing-type-page-wrapper">
    <div class="panel-heading"><h2>Edit Clothing Type</h2></div>
      <div class="panel-body">
        <%= render 'form' %>
        <%= link_to 'Back', clothing_types_path, class: "btn btn-lg btn-warning btn-block cancel-button" %>
      </div>
    </div>
  </div>
</div>

app/views/clothing_types/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h2>Clothing Types</h2></div>
  <div class="panel-body">
    <div class="row table-header">              
      <div class="col-md-1"><strong>#</strong></div>
      <div class="col-md-3"><strong>Name</strong></div>
      <div class="col-md-2"><strong>Price</strong></div>
      <div class="col-md-3"><strong>Description</strong></div>
      <div class="col-md-3"><strong>Action</strong></div>
    </div>
    <hr class="table-line"/>
    <div class="row">      
          <% @clothing_types.each_with_index do |clothing_type, index| %>
            <%= render clothing_type, index: index %> 
          <% end %>
    </div>        
    <hr/>
    <div class="row">
      <div class="col-md-3 col-md-offset-9">
        <%= link_to 'Add Clothing Type', new_clothing_type_path, class: "btn btn-lg btn-success btn-block" %>
      </div>
    </div>
  </div>
</div>

app/views/clothing_types/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <div class="panel panel-default clothing-type-page-wrapper">
    <div class="panel-heading"><h2>Add Clothing Type</h2></div>
      <div class="panel-body">
        <%= render 'form' %>
        <%= link_to 'Back', clothing_types_path, class: "btn btn-lg btn-warning btn-block cancel-button" %>
      </div>
    </div>
  </div>
</div>

app/views/employees/_employee.html.erb
<ul class="list-group">
  <li class="list-group-item">Name: <b><%= @employee.full_name %></b></li>
  <li class="list-group-item">Address: <b><%= format_address %></b></li>
  <li class="list-group-item">Age: <b><%= format_age %></b></li>
  <li class="list-group-item">Contact Details: <b><%= format_contact_details %></b></li>
  <li class="list-group-item">Birthday: <b><%= format_birthday %></b></li>
  <li class="list-group-item">   
    <div class="row field-margin no-print"> 
      <div class="col-md-2 col-md-offset-8">
        <%= link_to "Edit", edit_employee_path(@employee), class: "btn btn-lg btn-warning btn-block" %>
      </div>
      <div class="col-md-2">
        <%= link_to "Delete", employee_path(@employee), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-lg btn-danger btn-block" %>
      </div>    
    </div>
  </li>
</ul>

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, 'error') %> <%= 'prohibited this Clothing type from being saved' %>:</h2>
      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :first_name %><br/>
    <%= f.text_field :first_name, class: "form-control", placeholder: "e.g. \"Jay Paul\"", required: true %>
  </p>
  <p>
    <%= f.label :last_name %><br/>
    <%= f.text_field :last_name, class: "form-control", placeholder: "e.g. \"Ayingl\"", required: true %>
  </p>
  <p>
    <%= f.label :address %><br/>
    <%= f.text_field :address, class: "form-control", placeholder: "e.g. \"Tagbilaran City\"" %>
  </p>
  <p>
    <%= f.label :contact_details %><br/>
    <%= f.text_field :contact_details, class: "form-control", placeholder: "e.g. \"Mobile | Email | Home\"" %>
  </p>
  <p>
    <%= f.label :birthday %><br/>
    <%= f.date_field :birthday, class: "form-control" %>
  </p>
  <hr />
  <p>
    <%= f.submit class: "btn btn-lg btn-success btn-block" %>
    <%= link_to 'Cancel', employees_path, class: "btn btn-lg btn-danger btn-block" %>
  </p>
<% end %>

app/views/employees/_search_date_form.html.erb
<%= form_tag(employee_path(@employee), :method => "get", id: "sew-date-form") do %>
  <div class="col-md-4">
    <h4>Date: <%= time_tag @sewed_date.to_date %></h4>
  </div>
  <div class="col-md-4 col-md-offset-2 no-print">
    <%= select_tag :sew_date, options_for_select(@sewed_clothing_dates, @sewed_date), {class: "form-control", prompt: "Select date"} %>
  </div>
  <div class="col-md-2 no-print">
    <%= submit_tag "Search", class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<div class="col-md-4 col-md-offset-4">
<div class="panel panel-default employee-page-wrapper">
  <div class="panel-heading"><h2>Edit Employee</h2></div>
    <div class="panel-body">
      <%= render 'form' %>
      <%= link_to 'Back', employee_path(@employee), class: "btn btn-lg btn-warning btn-block cancel-button" %>
    </div>
  </div>
</div>
</div>

app/views/employees/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h2>Employees</h2></div>
    <div class="panel-body">
      <div class="row table-header">
        <div class="col-md-4">
          <h4>Name</h4>
        </div>
        <div class="col-md-4">
          <h4>Address</h4>
        </div>
        <div class="col-md-4">
          <h4>Contact Details</h4>
        </div>
      </div>
      <hr class="table-line"/>
      <% @employees.each do |employee| %>
        <% @employee = employee %>
        <div class="row">
            <div class="col-md-4"><%= link_to employee.full_name, employee_path(employee) %></div>
            <div class="col-md-4"><%= format_address %></div>
            <div class="col-md-4"><%= format_contact_details %></div>
        </div>
        <hr/>
      <% end %>

      <div class="row">        
        <div class="col-md-4  col-md-offset-8">
          <%= link_to "Add New Employee", new_employee_path, class: "btn btn-lg btn-success btn-block new-emp-btn" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/new.html.erb
<div class="col-md-4 col-md-offset-4">
<div class="panel panel-default employee-page-wrapper">
  <div class="panel-heading"><h2>Add New Employee</h2></div>
    <div class="panel-body">
      <%= render 'form' %>
    </div>
  </div>
</div>
</div>

app/views/employees/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading no-print"><h2>Employee's Profile</h2></div>
    <div class="panel-body">
      <div class="panel panel-default">
        <div class="panel-heading no-print"><h3>Personal Info</h3></div>
        <%= render @employee %>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading no-print"><h3>Sewed Clothing</h3></div>
        <ul class="list-group">
          <li class="list-group-item">
            <div class="row search-date-form">              
              <%= render "employees/search_date_form" %>              
            </div>
          </li>
          <li class="list-group-item">
            <div class="row table-header">
              <div class="col-md-1"><strong>#</strong></div>
              <div class="col-md-2"><strong>Owner Name</strong></div>
              <div class="col-md-2"><strong>Clothing Type</strong></div>
              <div class="col-md-1"><strong>Quantity</strong></div>
              <div class="col-md-1"><strong>Unit Price</strong></div>
              <div class="col-md-2"><strong>Total</strong></div>
              <div class="col-md-3"><strong>Action</strong></div>
            </div>
            <hr class="table-line"/>
            
              <% @sewed_clothings_on_date.each_with_index do |sewed_clothing, index| %>
                <div class="row sewed-clothings">          
                  <%= render sewed_clothing, index: index %>                
                </div> 
                <hr/>     
              <% end %>               
            
            <hr class="table-line"/>                      
            <div class="row total-div">
                <div class="col-md-6"></div>
                <div class="col-md-1 total-div-text">Total:</div>
                <div class="col-md-2 total-sewed-amount">
                  <strong><%= number_to_currency(sewed_clothing_total(@sewed_clothings_on_date), unit: "₱ ") %></strong>
                </div>
            </div>
          </li>
        </ul>
      </div>

      <div class="panel panel-default no-print">
        <div class="panel-heading"><h3>Add Sewed Clothing</h3></div>
        <div class="panel-body">
          <%= render "sewed_clothings/form" %>
        </div>
      </div>

    </div>
  </div>
  <a href="javascript:print()" class="btn btn-lg btn-success btn-block no-print">Print this Page</a>
</div>
<div class="signature yes-print">
  <p>
   Signed: <%= @employee.full_name %>, Employee
  </p>
  <br>
  <br>
  <p>
   Signed: Carmelita B. Aying, Wild Dust Tailoring
  </p>
</div>
<br>

app/views/layouts/_login_items.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WildDustPayroll</title>
  <%= stylesheet_link_tag    "application", media: :all, "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body data-no-turbolink="true">
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Wild Dust", root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class= "<%= active_link(employees_path) || active_link(root_path) %>" ><%= link_to "Employees",      employees_path      %></li>
          <li class= "<%= active_link(clothing_types_path) %>" ><%= link_to "Clothing Types", clothing_types_path %></li>
          <li class= "<%= active_link(about_path) %>" ><%= link_to "About", about_path %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <%= render "layouts/login_items" %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-10">      
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/sewed_clothings/_form.html.erb
  <%= form_for([@employee, @sewed_clothing]) do |f| %>  
    <div class="row">  
      <% if @sewed_clothing.errors.any? %>
            <div id="error_explanation">
              <h5><%= pluralize(@sewed_clothing.errors.count, 'error') %> <%= 'prohibited this Clothing type from being saved' %>:</h5>
              <ul>
              <% @sewed_clothing.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>                 
      <% end %>
    </div>

    <div class="row field-margin">
      <div class="col-md-3"><%= f.text_field :owner_name, class: "form-control", placeholder: "Owner name", required: true %></div>
      <div class="col-md-3"><%= f.collection_select :clothing_type_id, ClothingType.all, :id, :name, {prompt: true}, {class: "form-control", required: true} %></div>
      <div class="col-md-3"><%= f.text_field :quantity, class: "form-control", placeholder: "Quantity", required: true %></div>
      <div class="col-md-3"><%= f.submit class: "btn btn-success btn-block new-emp-btn" %></div>
    </div>
  <% end %>

app/views/sewed_clothings/_sewed_clothing.html.erb
<%= content_tag_for(:tr, sewed_clothing) do %>
  <div class="col-md-1"><span class="field-label">#: </span><%= index + 1 %></div>
  <div class="col-md-2"><span class="field-label">Owner Name: </span><%= sewed_clothing.owner_name %></div>
  <div class="col-md-2"><span class="field-label">Clothing Type: </span><%= sewed_clothing.clothing_type.name %></div>
  <div class="col-md-1"><span class="field-label">Quantity: </span><%= sewed_clothing.quantity %></div>
  <div class="col-md-1">
    <span class="field-label">Unit Price: </span><%= number_to_currency(sewed_clothing.clothing_type.unit_price, unit: "₱ ") %>
  </div>
  <div class="col-md-2"><span class="field-label">Total: </span><%= number_to_currency(sewed_clothing.total, unit: "₱ ") %></div>
  <div class="col-md-3">
    <div class="row no-print field-margin">
      <div class="col-md-6">
        <%= link_to "Edit", edit_employee_sewed_clothing_path(@employee, sewed_clothing), class: "btn btn-warning btn-block" %>
      </div>
      <div class="col-md-6">
        <%= link_to "Delete", employee_sewed_clothing_path(@employee, sewed_clothing), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-block" %>
      </div>
    </div>
  </div>  
<% end %>